# syntax=docker/dockerfile:1

# Padrão 3: Utilizando a base ros-core ao invés de ros-base para reduzir peso inicial
FROM ros:humble-ros-core

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# Padrão 4: Download oficial da internet, mas protegido por cache mount persistente.
# Substitui totalmente a necessidade do seu antigo apt-ros offline.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    ros-humble-rosbridge-suite \
    ros-humble-rmw-cyclonedds-cpp && \
    rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && ros2 launch rosbridge_server rosbridge_websocket_launch.xml"]