services:
  antigravity-mcp:
    build:
      context: .
      dockerfile: Dockerfile.antigravity
    container_name: antigravity-mcp
    networks:
      - robotic-net
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - ./ros-mcp-server/robot_specifications:/app/ros-mcp-server/robot_specifications
      - antigravity-config:/root/.gemini

  rosbridge:
    build:
      context: .
      dockerfile: Dockerfile.rosbridge
    container_name: rosbridge
    networks:
      - robotic-net
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    # A porta agora é explicitamente mapeada do container para a máquina hospedeira
    ports:
      - "9090:9090"
    restart: unless-stopped

# Definição de rede própria (bridge) para isolar o ecossistema do seu projeto
networks:
  robotic-net:
    driver: bridge

volumes:
  antigravity-config: